version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: car_postgres
    environment:
      POSTGRES_DB: car_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5433:5432"
    volumes:
      - car_pg_data:/var/lib/postgresql/data

volumes:
  car_pg_data:
